export const SET_CART_ITEM = "SET_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";
export const TOTAL_CART_PRICE = "TOTAL_CART_PRICE";
